name: Pull Request Check

on: [ pull_request ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          # for self-hosted, the cache path is shared across projects
          # and it works well without the cache of github actions
          # Enable it if we're going to use Github only
          cache: true

      - name: Golangci Lint
        # https://golangci-lint.run/
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
